apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fleetman-mongodb
  name: fleetman-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fleetman-mongodb
    spec:
      containers:
        - image: mongo:3.6.23
          name: fleetman-mongodb
          ports:
            - containerPort: 27017
              protocol: TCP
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data
      restartPolicy: Always
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-data
