apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fleetman-queue
  name: fleetman-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-queue
  template:
    metadata:
      labels:
        app: fleetman-queue
    spec:
      containers:
        - image: supinfo4kube/queue:1.0.1
          name: fleetman-queue
          ports:
            - containerPort: 8161
              protocol: TCP
            - containerPort: 61616
              protocol: TCP
      restartPolicy: Always
