apiVersion: apps/v1
kind: Deployment
metadata:
  name: trucks-queue
  namespace: fleetman
  labels:
    app: trucks-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trucks-queue
  template:
    metadata:
      labels:
        app: trucks-queue
    spec:
      containers:
      - name: trucks-queue
        image: supinfo4kube/queue:1.0.1
        ports:
        - containerPort: 61616 # port pour la communication JMS
        - containerPort: 8161  # port pour la console web
        # resources:
        #   requests:
        #     memory: "256Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "512Mi"
        #     cpu: "500m"
